[project]
channels = ["conda-forge", "bioconda"]
description = "Generate alternative alignments and HMMER HMMs for a specified Pfam accession or an input MSA"
name = "diversify_pfam"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
biopython = ">=1.84,<2"
click = ">=8.1.7,<9"
hhsuite = ">=3.3.0,<4"
hmmer = ">=3.4,<4"
numpy = ">=2.1.1,<3"
polyleven = ">=0.8,<0.9"
pyhmmer = ">=0.10.14,<0.11"
requests = ">=2.32.3,<3"
scikit-learn = ">=1.5.2,<2"
seqkit = ">=2.8.2,<3"
sh = ">=2.0.7,<3"
